
// Generated by https://quicktype.io

export interface User {
    use_id: number;
    use_id_: string;
    use_name: string;
    use_lastname: string;
    use_sta_id: number;
    use_username: string;
    use_creation_date: string;
}

